### ISSUE TITLE
Error while trying to get the Windows 11 ISO Download Link.

### ISSUE THREAD

**Issue by ThetaHalo** [ianis58/tiny11builder#17]
I get the following error when trying to run the powershell script, I believe it's related to #4 but I'm not sure.

```txt
[Info] Trying to obtain Windows 11 iso download link...
Unhandled exception. System.TimeoutException: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for Locator("#product-edition")
  locator resolved to <select id="product-edition" href="#product-info-content">.</select>
  selecting specified option(s)
    did not find some options - waiting...
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary) in /_/src/Playwright/Transport/Connection.cs:line 143
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 465
   at Microsoft.Playwright.Transport.Channels.FrameChannel.SelectOptionAsync(String selector, IEnumerable`1 values, Nullable`1 noWaitAfter, Nullable`1 strict, Nullable`1 force, Nullable`1 timeout) in /_/src/Playwright/Transport/Channels/FrameChannel.cs:line 469
   at Microsoft.Playwright.Core.Frame.SelectOptionAsync(String selector, IEnumerable`1 values, FrameSelectOptionOptions options) in /_/src/Playwright/Core/Frame.cs:line 154
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
Unable to build the tiny11 iso (an error occured while trying to download the original iso using WindowsIsoDownloader).
Removing work folders...
```

**Comment by ianis58** [comment]
Thanks for opening an issue. The fix has been made and it should work now (no change on this repo, changes are on https://github.com/ianis58/WindowsIsoDownloader so you should not need to redownload the tool).
